#include <stdio.h>
#include <stdint.h>
#include "gpio.h"
#include "sram.h"
#include "sdcard.h"
#include "supercic.h"   // TODO: header where control the /RESET line
// #include "stm32f4xx_hal.h"

// Maximum size you plan to support (e.g. 512KB for SRAM)
#define MAX_ROM_SIZE (512 * 1024)

void HAL_Init(void) {
    // TODO
}

void HAL_Delay(uint32_t ms) { 
    // TODO: sleep(ms); 
}

void SystemClock_Config(void){
  // TODO function that configures the clock to X MHz, etc.
}

static void MX_GPIO_Init(void){
    // TODO: (Generated by Cube or written by hand)
}

/**
  * Enable DMA controller clock
  */
static void MX_DMA_Init(void){
    //TODO 
}

static void MX_FSMC_Init(void){
    // TODO
}

static int SDCARD_Init(void){
    // TODO
    return -1;
}